apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: nodejs-example-app10-pipeline-run-init
  namespace: demo-dev
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
  labels:
    tekton.dev/pipeline: nodejs-example-app10-pipeline
    type: pipeline
spec:
  params:
    - name: source-repo
      value: 'https://github.com/intive-RedHat-Devex-demo/nodejs-example-app10.git'
    - name: source-branch
      value: main
    - name: output-image
      value: image-registry.openshift-image-registry.svc:5000/demo-dev/nodejs-example-app10
  pipelineRef:
    name: nodejs-example-app10-pipeline
  serviceAccountName: pipeline
  workspaces:
    - name: source-folder
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi
